[build.environment]
NODE_VERSION = "20"

[context.production]
  publish = "output/"
  command = "make publish"

[context.deploy-preview]
  publish = "dist/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200