<template>
  <q-page>
    <q-page-container class="p-6">
<strong>TERMS AND CONDITIONS</strong><br />

<strong>Last updated</strong> <strong>May 18, 2023</strong><br />

<strong><span>AGREEMENT TO OUR LEGAL TERMS</span></strong><br />

<span>We are All Information Services LLC, doing business as AIS Labs("<strong>Company</strong>," "<strong>we</strong>," "<strong>us</strong>," "<strong>our</strong>").</span>
<span>We operatethe website project.aislabs.com (the "<strong>Site</strong>"), the mobile application AIS Labs Project Central (the "<strong>App</strong>"), as well as any other related products and services that refer or link to these legal terms (the "<strong>Legal Terms</strong>") (collectively, the "<strong>Services</strong>").</span><br />
<span>You can contact us by email at __________ or by mail to __________, __________, __________.</span>
<br /><span>These Legal Terms constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("<strong>you</strong>"), and All Information Services LLC, concerning your access to and use of the Services. You agree that by accessing the Services, you have read, understood, and agreed to be bound by all of these Legal Terms. IF YOU DO NOT AGREE WITH ALL OF THESE LEGAL TERMS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.</span>
<br /><span>Supplemental terms and conditions or documents that may be posted on the Services from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Legal Terms at any time and for any reason. We will alert you about any changes by updating the "Last updated" date of these Legal Terms, and you waive any right to receive specific notice of each such change. It is your responsibility to periodically review these Legal Terms to stay informed of updates. You will be subject to, and will be deemed to have been made aware of and to have accepted, the changes in any revised Legal Terms by your continued use of the Services after the date such revised Legal Terms are posted.</span>
<br /><span>The
Services are intended for users who are at least 18 years old. Persons under the age
of 18 are not permitted to use or register for the Services.</span>

<br />We recommend that you print a copy of these Legal Terms for your records.

<br /><br /><strong>TABLE OF CONTENTS</strong><br />

<a href="#services"><span>
  <span><span >1. OUR SERVICES</span></span></span></a><a href="#ip">
    <span >2. INTELLECTUAL PROPERTY RIGHTS</span></a><a href="#userreps"></a><a href="#userreps"><span><span >3. USER REPRESENTATIONS</span></span></a><span><span ></span></span><a href="#userreg"><span><span >4. USER REGISTRATION</span></span></a>
    <span><span ></span></span> <a href="#products"></a><a href="#products"><span><span >5. PRODUCTS</span></span></a> <a href="#purchases"></a><a href="#purchases"><span><span >6. PURCHASES AND PAYMENT</span>
    </span></a><span><span ></span></span><a href="#returnyes"><span><span >7. RETURN/REFUNDS POLICY</span></span></a><span><span ></span></span><span><span ></span></span> <a href="#software"></a>
    <a href="#software"><span><span >8. SOFTWARE</span></span></a> <a href="#prohibited"><span><span >9. PROHIBITED ACTIVITIES</span>
      </span></a> <a href="#ugc"></a><a href="#ugc"><span><span >10. USER GENERATED CONTRIBUTIONS</span></span></a> <a href="#license"></a><a href="#license"><span>
        <span >11. CONTRIBUTION LICENSE</span></span></a> <a href="#reviews"><span><span ></span></span></a> <a href="#mobile">
          <span><span >12. MOBILE APPLICATION LICENSE</span></span></a> <a href="#socialmedia"></a><a href="#socialmedia"><span><span ></span></span></a> <a href="#thirdparty">
            </a><a href="#thirdparty"><span><span >13. THIRD-PARTY WEBSITES AND CONTENT</span></span></a> <a href="#advertisers"></a><a href="#advertisers"><span><span ></span></span></a>
            <a href="#sitemanage"></a><a href="#sitemanage"><span><span >14. SERVICES MANAGEMENT</span></span></a> <a href="#ppyes"></a><a href="#ppyes"><span><span >15. PRIVACY POLICY</span></span></a>
            <a href="#ppno"></a><a href="#ppno"><span><span ></span></span></a> <a href="#dmca"></a><a href="#dmca"><span><span ></span></span></a><span><span ></span></span> <a href="#terms"></a><a href="#terms"><span><span >16. TERM AND TERMINATION</span></span></a> <a href="#modifications"></a><a href="#modifications"><span><span >17. MODIFICATIONS AND INTERRUPTIONS</span></span></a> <a href="#law"></a><a href="#law"><span><span >18. GOVERNING LAW</span></span></a> <a href="#disputes"></a><a href="#disputes"><span><span >19. DISPUTE RESOLUTION</span></span></a> <a href="#corrections"></a><a href="#corrections"><span><span >20. CORRECTIONS</span></span></a> <a href="#disclaimer"></a><a href="#disclaimer"><span><span >21. DISCLAIMER</span></span></a> <a href="#liability"></a><a href="#liability"><span><span >22. LIMITATIONS OF LIABILITY</span></span></a> <a href="#indemnification"></a><a href="#indemnification"><span><span >23. INDEMNIFICATION</span></span></a> <a href="#userdata"></a><a href="#userdata"><span><span >24. USER DATA</span></span></a> <a href="#electronic"></a><a href="#electronic"><span><span >25. ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES</span></span></a> <a href="#california"></a><a href="#california"><span><span >26. CALIFORNIA USERS AND RESIDENTS</span></span></a> <a href="#misc"><span><span >27. MISCELLANEOUS</span></span></a><a href="#contact"><span><span >28. CONTACT US</span></span></a><a name="_b6y29mp52qvx"></a><br /><br /><strong><span>1. OUR SERVICES</span></strong><br /><span>The information provided when using the Services is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the Services from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.</span><span></span><br /><span>The Services are not tailored to comply with industry-specific regulations (Health Insurance Portability and Accountability Act (HIPAA), Federal Information Security Management Act (FISMA), etc.), so if your interactions would be subjected to such laws, you may not use the Services. You may not use the Services in a way that would violate the Gramm-Leach-Bliley Act (GLBA).<br /><strong><span id="ip">2. INTELLECTUAL PROPERTY RIGHTS</span></strong><br /><strong>Our intellectual property</strong>
    <br /><span>We are the owner or the licensee of all intellectual property rights in our Services, including all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics in the Services (collectively, the "Content"), as well as the trademarks, service marks, and logos contained therein (the "Marks").</span>
    <br /><span>Our Content and Marks are protected by copyright and trademark laws (and various
other intellectual property rights and unfair competition laws) and treaties in the United
States and around the world.</span>
<br /><span>The Content and Marks are provided in or through the Services "AS IS" for your internal business purpose only.</span><br />
<strong>Your use of our Services</strong><br /><span>Subject to your compliance with these Legal Terms, including the "</span><a href="#prohibited">
  <span>PROHIBITED ACTIVITIES</span></a><span>" section below, we grant you a non-exclusive, non-transferable, revocable license
     to:</span><ul><li><span>access the Services; and</span></li>
     <li><span>download or print a copy of any portion of the Content to which you have properly gained access.</span></li></ul>
     <span>solely for your internal business purpose.</span>
     <br /><span>Except as set out in this section or elsewhere in our Legal Terms, no part of the Services and no Content or Marks may be copied, reproduced,
aggregated, republished, uploaded, posted, publicly displayed, encoded,
translated, transmitted, distributed, sold, licensed, or otherwise exploited
for any commercial purpose whatsoever, without our express prior written
permission.</span><br />
<span>If you wish to make any use of the Services, Content, or Marks other than as set out in this section or elsewhere in our Legal Terms, please address your request to: __________. If we ever grant you the permission to post, reproduce, or publicly display any part of our Services or Content, you must identify us as the owners or licensors of the Services, Content, or Marks and ensure that any copyright or proprietary notice appears or is visible on posting, reproducing, or displaying our Content.</span><br /><span>
  We reserve all rights not expressly granted to you in and to the Services, Content, and Marks.</span>
<br /><span>Any breach of these Intellectual Property Rights will constitute a material breach of our Legal Terms and your right to use our Services will terminate immediately.</span><br /><span>
  <strong>Your submissions</strong></span><br /><span>Please review this section and the "<a href="#prohibited">PROHIBITED ACTIVITIES</a>" section carefully prior to using our Services to understand the (a) rights you give us and (b) obligations you have when you post or upload any content through the Services.</span><br /><span><strong>Submissions:</strong> By directly sending us any question, comment, suggestion, idea, feedback, or other information about the Services ("Submissions"), you agree to assign to us all intellectual property rights in such Submission. You agree that we shall own this Submission and be entitled to its unrestricted use and dissemination for any lawful purpose, commercial or otherwise, without acknowledgment or compensation to you.</span><br /><span><strong>You are responsible for what you post or upload:</strong> By sending us Submissions through any part of the Services you:</span><ul><li><span>confirm that you have read and agree with our "</span><a href="#prohibited"><span>PROHIBITED ACTIVITIES</span></a><span>" and will not post, send, publish, upload, or transmit through the Services any Submission that is illegal, harassing, hateful, harmful, defamatory, obscene, bullying, abusive, discriminatory, threatening to any person or group, sexually explicit, false, inaccurate, deceitful, or misleading;</span></li><li><span>to the extent permissible by applicable law, waive any and all moral rights to any such Submission;</span></li><li><span>warrant that any such Submission are original to you or that you have the necessary rights and licenses to submit such Submissions and that you have full authority to grant us the above-mentioned rights in relation to your Submissions; and</span></li><li><span>warrant and represent that your Submissions do not constitute confidential information.</span></li></ul>You are solely responsible for your Submissions and you expressly agree to reimburse us for any and all losses that we may suffer because of your breach of (a) this section, (b) any third party’s intellectual property rights, or (c) applicable law.<br /><a name="_5hg7kgyv9l8z"></a><strong><span><strong><span><strong><span><strong><span>3.</span></strong></span></strong></span> </strong>USER REPRESENTATIONS</span></strong><br /><span>
    By using the Services, you represent and warrant that:</span> <span>1</span><span>) all registration information you submit
will be true, accurate, current, and complete; (</span><span>2</span><span>) you will maintain the accuracy of such information and promptly update such registration information as necessary;</span> 
<span>3</span><span>) you have the legal capacity and you agree to comply with these Legal Terms;</span> <span>4</span><span>) you are not a
minor in the jurisdiction in which you reside; (</span><span>5</span><span>) you will not access the Services through automated or non-human means, whether through a bot, script or
otherwise; (</span><span>) you will not use the Services for any illegal or unauthorized purpose; and (</span><span>7</span><span>) your use of the Services will not violate any applicable law or regulation.</span><span></span><br />
<span>If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Services (or any portion thereof).</span>
<br /><strong><span><strong><span><strong><span><strong><span>4.</span></strong></span></strong></span> </strong>USER REGISTRATION</span></strong><br />
<span>You may be required to register to use the Services. You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim,
  or change a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable.</span><span></span><span></span>
  <br /><span><strong>5. PRODUCTS</strong></span><br /><span></span><span>We make every effort to display as accurately as possible the colors, features, specifications, and details of the
    products available on the Services. However, we do not guarantee that the colors, features, specifications, and details of the products will be accurate, complete, reliable, current, or free of other errors,
     and your electronic display may not accurately reflect the actual colors and details of the products. All products are subject to availability, and we cannot guarantee that items will be in stock.
     We reserve the right to discontinue any products at any time for any reason. Prices for all products are subject to change.</span><span></span><br /><a name="_ynub0jdx8pob"></a><strong><span><strong><span>
      <strong><span><strong><span>6.</span></strong></span></strong></span> </strong>PURCHASES AND PAYMENT</span></strong><br /><span>
  We accept the following forms of payment:</span>
  <br /><span>-  Visa</span><span>-  Mastercard</span><span>
  -  American Express</span><span>-  Discover</span>
  <span></span><span><br />
  </span><span>You agree to provide current, complete, and accurate purchase and account information for all purchases made via the Services. You further agree to promptly
    update account and payment information, including email address, payment method, and payment card expiration date, so that we can complete your transactions and contact you as needed.
    Sales tax will be added to the price of purchases as deemed required by us. We may change prices at any time. All payments shall be </span>
    <span>in US dollars.</span><br />
<span>You agree to pay all charges at the prices then in effect for your purchases and any applicable shipping fees, and you authorize us to charge your chosen payment provider
  for any such amounts upon placing your order. If your order is subject to recurring charges, then you consent to our charging your payment method on a recurring basis without requiring your prior approval for each recurring charge,
  until such time as you cancel the applicable order. We reserve the right to correct any errors or mistakes in pricing, even if we have already requested or received payment.
  </span><br />
  <span>
    We reserve the right to refuse any order placed through the Services. We may, in our sole discretion, limit or cancel quantities purchased per person, per household, or per order.
    These restrictions may include orders placed by or under the same customer account, the same payment method, and/or orders that use the same billing or shipping address. We reserve the
    right to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers, or distributors.</span>
    <span>
    </span><span></span><span></span><br />
    <span><strong>7. RETURN/REFUNDS POLICY</strong></span><br />Please review our Return Policy posted on the Services prior to making any purchases.</span><span></span><br />
    <strong><span>8. SOFTWARE</span></strong><br />
    <span>We may include software for use in connection with our Services. If such software is accompanied by an end user license agreement ("EULA"), the terms of the EULA will govern your use of the software.
      If such software is not accompanied by a EULA, then we grant to you a non-exclusive, revocable, personal, and non-transferable license to use such software solely in connection with our services and in accordance with these Legal Terms.
      Any software and any related documentation is provided "AS IS" without warranty of any kind, either express or implied, including, without limitation, the implied warranties of merchantability, fitness for a particular purpose, or non-infringement.
      You accept any and all risk arising out of use or performance of any software. You may not reproduce or redistribute any software except in accordance with the EULA or these Legal Terms.</span><br /><strong><span><strong><span><strong><span>
        <strong><span>9.</span></strong></span></strong></span> </strong>
        PROHIBITED ACTIVITIES</span></strong><br /><span>
          You may not access or use the Services for any purpose other than that for which we make the Services available. The Services may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.
          </span><br /><span>
            As a user of the Services, you agree not to:</span>
            <ul><li><span>
              <span>
                Systematically retrieve data or other content from the Services to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</span></span></li>
                <li><span>
                  <span>
                    <span>
                      <span><span>
                        Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.</span></span></span></span></span></li>
                        <li><span>
                          <span><span>
                            <span><span>
                              Circumvent, disable, or otherwise interfere with security-related features of the Services, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Services and/or the Content contained therein.
                              </span></span></span></span></span></li>
                              <li><span>
                                <span><span><span>
                                  <span>
                                    Disparage, tarnish, or otherwise harm, in our opinion, us and/or the Services.</span></span></span></span></span></li>
                                    <li><span><span>
                                      <span><span>
                                        <span>
                                          Use any information obtained from the Services in order to harass, abuse, or harm another person.</span></span></span></span></span></li>
                                          <li><span><span>
                                            <span>
                                              <span><span>
                                                Make improper use of our support services or submit false reports of abuse or misconduct.</span></span></span></span></span></li>
                                                <li>
                                                  <span>
                                                    <span>
                                                      <span>
                                                        <span>
                                                          <span>Use the Services in a manner inconsistent with any applicable laws or regulations.</span></span></span></span></span></li><li><span>
                                                            <span><span>
                                                              <span>
                                                                <span>Engage in unauthorized framing of or linking to the Services.</span></span></span></span></span></li>
                                                                <li><span>
                                                                  <span><span><span>
                                                                    <span>
                                                                      Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party’s uninterrupted use
                                                                      and enjoyment of the Services or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Services.
                                                                      </span></span></span></span></span></li>
                                                                      <li><span>
                                                                        <span>
                                                                          <span>
                                                                            <span><span>
                                                                              Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.</span></span></span></span></span></li>
                                                                              <li><span><span>
                                                                                <span>
                                                                                  <span><span>
                                                                                    Delete the copyright or other proprietary rights notice from any Content.</span></span></span></span></span></li>
                                                                                    <li><span><span>
                                                                                      <span><span>
                                                                                        <span>
                                                                                          Attempt to impersonate another user or person or use the username of another user.</span></span></span></span></span></li>
                                                                                          <li><span>
                                                                                            <span>
                                                                                              <span>
                                                                                                <span>
                                                                                                  <span>
                                                                                                    Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats ("gifs"), 1×1 pixels,
                                                                                                    web bugs, cookies, or other similar devices (sometimes referred to as "spyware" or "passive collection mechanisms" or "pcms").</span></span></span></span></span></li>
                                                                                                    <li><span><span>
                                                                                                      <span>
                                                                                                        <span>
                                                                                                          <span>
                                                                                                            Interfere with, disrupt, or create an undue burden on the Services or the networks or services connected to the Services.</span></span></span></span></span></li>
                                                                                                            <li><span><span>
                                                                                                              <span>
                                                                                                                <span>
                                                                                                                  <span>
                                                                                                                    Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Services to you.</span></span></span></span></span></li>
                                                                                                                    <li><span>
                                                                                                                      <span>
                                                                                                                        <span>
                                                                                                                          <span>
                                                                                                                            <span>
                                                                                                                              Attempt to bypass any measures of the Services designed to prevent or restrict access to the Services, or any portion of the Services.</span></span></span></span></span></li>
                                                                                                                              <li><span><span>
                                                                                                                                <span>
                                                                                                                                  <span>
                                                                                                                                    <span>
                                                                                                                                      Copy or adapt the Services' software, including but not limited to Flash, PHP, HTML, JavaScript, or other code.</span></span></span></span></span></li>
                                                                                                                                      <li><span>
                                                                                                                                        <span>
                                                                                                                                          <span>
                                                                                                                                            <span><span>
                                                                                                                                              Except as permitted by applicable law, decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Services.</span></span></span></span></span></li>
                                                                                                                                              <li><span>
                                                                                                                                                <span>
                                                                                                                                                  <span><span>
                                                                                                                                                    <span>
                                                                                                                                                      Except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Services, or use or launch any unauthorized script or other software.</span></span></span></span></span></li>
                                                                                                                                                      <li><span>
                                                                                                                                                        <span>
                                                                                                                                                          <span>
                                                                                                                                                            <span>
                                                                                                                                                              <span>
                                                                                                                                                                Use a buying agent or purchasing agent to make purchases on the Services.</span></span></span></span></span></li>
                                                                                                                                                                <li><span>
                                                                                                                                                                  <span>
                                                                                                                                                                    <span>
                                                                                                                                                                      <span>
                                                                                                                                                                        <span>
                                                                                                                                                                          Make any unauthorized use of the Services, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.</span></span></span></span></span></li>
                                                                                                                                                                          <li><span>
                                                                                                                                                                            <span><span><span>
                                                                                                                                                                              <span>
                                                                                                                                                                                Use the Services as part of any effort to compete with us or otherwise use the Services and/or the Content for any revenue-generating endeavor or commercial enterprise.</span>
                                                                                                                                                                                <span></span></span></span></span></span></li>
                                                                                                                    <li>
                                                                                                                      <span>
                                                                                                                        Use the Services to advertise or offer to sell goods and services.</span>
                                                                                                                        </li>
                                                                                                                        <li><span>
                                                                                                                          Sell or otherwise transfer your profile.</span></li></ul><br /><strong><span>
                                                                                                                            <strong><span>
                                                                                                                              <strong><span><strong>
                                                                                                                                <span>10. </span></strong>
                                                                                                                                </span></strong></span> </strong>
                                                                                                                                USER GENERATED CONTRIBUTIONS</span></strong><br />
                                                                                                                                <span><span>The Services does not offer users to submit or post content. We may provide you with the opportunity to create,
                                                                                                                                  submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials to us or on the Services,
                                                                                                                                  including but not limited to text, writings, video, audio, photographs, graphics, comments, suggestions, or personal
                                                                                                                                  information or other material (collectively, "Contributions"). Contributions may be viewable by other users of the Services
                                                                                                                                  and through third-party websites. As such, any Contributions you transmit may be treated in accordance with the Services'
                                                                                                                                  Privacy Policy. When you create or make available any Contributions, you thereby represent and warrant that:
                                                                                                                                  <span></span></span></span><ul><li><span>
                                                                                                                                    <span><span >The creation, distribution, transmission, public display, or
                                                                                                                                      performance, and the accessing, downloading, or copying of your Contributions do not and will not
                                                                                                                                      infringe the proprietary rights, including but not limited to the copyright, patent, trademark, trade secret, or
                                                                                                                                      moral rights of any third party.</span></span></span></li><li>
                                                                                                                                        <span><span><span >You are the creator and owner of or have the necessary licenses,
                                                                                                                                          rights, consents, releases, and permissions to use and to authorize us, the Services, and other users of
                                                                                                                                          the Services to use your Contributions in any manner contemplated by the Services and these Legal Terms.</span></span>
                                                                                                                                          </span></li><li><span>
                                                                                                                                            <span><span >You have the written consent, release, and/or permission of each and
                                                                                                                                              every identifiable individual person in your Contributions to use the name or likeness of each and every
                                                                                                                                              such identifiable individual person to enable inclusion and use of your Contributions in any manner contemplated
                                                                                                                                              by the Services and these Legal Terms.</span></span></span></li>
                                                                                                                                              <li><span>
                                                                                                                                                <span><span >Your Contributions are not false, inaccurate, or misleading.</span></span></span></li>
                                                                                                                                                <li><span >Your Contributions are not unsolicited or unauthorized advertising, promotional materials, pyramid schemes, chain letters, spam, mass mailings, or other forms of solicitation.</span></li>
                                                                                                                                                <li><span >Your Contributions are not obscene, lewd, lascivious, filthy, violent, harassing, libelous, slanderous, or otherwise objectionable (as determined by us).</span></li>
                                                                                                                                                <li><span >Your Contributions do not ridicule, mock, disparage, intimidate, or abuse anyone.</span></li>
                                                                                                                                                <li><span >Your Contributions are not used to harass or threaten (in the legal sense of those terms) any other person and to promote violence against a specific person or class of people.</span></li>
                                                                                                                                                <li><span >Your Contributions do not violate any applicable law, regulation, or rule.</span></li>
                                                                                                                                                <li><span >Your Contributions do not violate the privacy or publicity rights of any third party.</span></li>
                                                                                                                                                <li><span >Your Contributions do not violate any applicable law concerning child pornography, or otherwise intended to protect the health or well-being of minors.</span></li>
                                                                                                                                                <li><span >Your Contributions do not include any offensive comments that are connected to race, national origin, gender, sexual preference, or physical handicap.</span></li>
                                                                                                                                                <li><span >Your Contributions do not otherwise violate, or link to material that violates, any provision of these Legal Terms, or any applicable law or regulation.</span></li>
                                                                                                                                                </ul>
                                                                                                                                                <span>Any use of the Services in violation of the foregoing violates these Legal Terms and may result in, among other things, termination or suspension of your rights to
                                                                                                                                                  use the Services.</span><br /><strong><span><strong><span><strong><span><strong><span>11.</span></strong></span></strong></span> </strong>CONTRIBUTION LICENSE</span></strong><br />
                                                                                                                                                  <span><span>You and Services agree that we may access, store, process, and use any information and personal data that you provide following the terms of the Privacy Policy and your choices
                                                                                                                                                    (including settings).</span></span><br /><span>By submitting suggestions or other feedback regarding the Services, you agree that we can use and share such feedback for any purpose without
                                                                                                                                                      compensation to you.</span><br /><span>We do not assert any ownership over your Contributions. You retain full ownership of all of your Contributions and any intellectual property rights or
                                                                                                                                                        other proprietary rights associated with your Contributions. We are not liable for any statements or representations in your Contributions provided by you in any area on the Services. You are
                                                                                                                                                        solely responsible for your Contributions to the Services and you expressly agree to exonerate us from any and all responsibility and to refrain from any legal action against us regarding your Contributions.</span>
                                                                                                                                                        <br /><span><span><span></span></span></span>

                                                                                                                                                        <strong><span><strong><span><strong><span>12.</span></strong></span></strong></span>
                                                                                                                                                        MOBILE APPLICATION LICENSE</strong><br /><strong>Use License</strong><br /><span>If you access the Services via the App, then we grant you a revocable, non-exclusive, non-transferable,
                                                                                                                                                          limited right to install and use the App on wireless electronic devices owned or controlled by you, and to access and use the App on such devices strictly in accordance with the terms
                                                                                                                                                          and conditions of this mobile application license contained in these Legal Terms. You shall not: (1) except as permitted by applicable law, decompile, reverse engineer, disassemble, attempt
                                                                                                                                                          to derive the source code of, or decrypt the App; (2) make any modification, adaptation, improvement, enhancement, translation, or derivative work from the App; (3) violate any applicable laws, rules, or regulations
                                                                                                                                                          in connection with your access or use of the App; (4) remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) posted by us or the licensors of the App; (5) use the App for any
                                                                                                                                                          revenue-generating endeavor, commercial enterprise, or other purpose for which it is not designed or intended; (6) make the App available over a network or other environment permitting access or use by multiple devices or users at the same time; (7) use the App for creating a product,
                                                                                                                                                          service, or software that is, directly or indirectly, competitive with or in any way a substitute for the App; (8) use the App to send automated queries to any website or to send any unsolicited commercial email; or (9)
                                                                                                                                                          use any proprietary information or any of our interfaces or our other intellectual property in the design, development, manufacture, licensing, or distribution of any applications, accessories, or devices for use with the App.</span>
                                                                                                                                                          <br /><span><strong>Apple and Android Devices</strong></span><br /><span>The following terms apply when you use the App obtained from either the Apple Store or Google Play (each an "App Distributor") to access the Services:
                                                                                                                                                            (1) the license granted to you for our App is limited to a non-transferable license to use the application on a device that utilizes the Apple iOS or Android operating systems, as applicable, and in accordance with the
                                                                                                                                                            usage rules set forth in the applicable App Distributor’s terms of service; (2) we are responsible for providing any maintenance and support services with respect to the App as specified in the terms and conditions of this
                                                                                                                                                            mobile application license contained in these Legal Terms or as otherwise required under applicable law, and you acknowledge that each App Distributor has no obligation whatsoever to furnish any maintenance and support
                                                                                                                                                            services with respect to the App; (3) in the event of any failure of the App to conform to any applicable warranty, you may notify the applicable App Distributor, and the App Distributor, in accordance with its terms and
                                                                                                                                                            policies, may refund the purchase price, if any, paid for the App, and to the maximum extent permitted by applicable law, the App Distributor will have no other warranty obligation whatsoever with respect to the App; (4)
                                                                                                                                                            you represent and warrant that (i) you are not located in a country that is subject to a US government embargo, or that has been designated by the US government as a "terrorist supporting" country and (ii) you are not listed
                                                                                                                                                            on any US government list of prohibited or restricted parties; (5) you must comply with applicable third-party terms of agreement when using the App, e.g., if you have a VoIP application, then you must not be in violation of
                                                                                                                                                            their wireless data service agreement when using the App; and (6) you acknowledge and agree that the App Distributors are third-party beneficiaries of the terms and conditions in this mobile application license contained in
                                                                                                                                                            these Legal Terms, and that each App Distributor will have the right (and will be deemed to have accepted the right) to enforce the terms and conditions in this mobile application license contained in these Legal Terms against
                                                                                                                                                            you as a third-party beneficiary thereof.</span><br /><span><span><span></span></span></span>
                                                                                                                                                            <strong><span><strong><span><strong><span>13.</span></strong></span></strong> </span>THIRD-PARTY WEBSITES AND CONTENT</strong><br /><span>The Services may contain (or you may be sent via the Site or App) links to other
                                                                                                                                                               websites ("Third-Party Websites") as well as articles, photographs, text, graphics, pictures, designs, music, sound, video, information, applications, software, and other content or items belonging to or
                                                                                                                                                               originating from third parties ("Third-Party Content"). Such <span>Third-Party</span> Websites and <span>Third-Party</span> Content are not investigated,
                                                                                                                                                               monitored, or checked for accuracy, appropriateness, or completeness by us, and we are not responsible for any Third-Party Websites accessed through the Services or any
                                                                                                                                                               <span>Third-Party</span> Content posted on, available through, or installed from the Services, including the content, accuracy, offensiveness, opinions, reliability,
                                                                                                                                                               privacy practices, or other policies of or contained in the <span>Third-Party</span> Websites or the <span>Third-Party</span> Content. Inclusion of,
                                                                                                                                                               linking to, or permitting the use or installation of any <span>Third-Party</span> Websites or any <span>Third-Party </span>
                                                                                                                                                               Content does not imply approval or endorsement thereof by us. If you decide to leave the Services and access the <span>Third-Party</span> Websites or to use or install any
                                                                                                                                                               <span>Third-Party</span> Content, you do so at your own risk, and you should be aware these Legal Terms no longer govern. You should review the applicable terms and
                                                                                                                                                               policies, including privacy and data gathering practices, of any website to which you navigate from the Services or relating to any applications you use or install from the Services. Any purchases
                                                                                                                                                               you make through <span>Third-Party</span> Websites will be through other websites and from other companies, and we take no responsibility whatsoever in relation to such
                                                                                                                                                               purchases which are exclusively between you and the applicable third party. You agree and acknowledge that we do not endorse the products or services offered on <span>
                                                                                                                                                                Third-Party</span> Websites and you shall hold us blameless from any harm caused by your purchase of such products or services. Additionally, you shall hold us blameless from any losses sustained by you or
                                                                                                                                                                harm caused to you relating to or resulting in any way from any <span>Third-Party</span> Content or any contact with <span>Third-Party</span>
                                                                                                                                                                Websites.</span><br /><strong><span><strong><span><strong><span><strong><span>14.</span></strong></span></strong></span> </strong>SERVICES MANAGEMENT</span></strong><br />We reserve the right, but not the obligation,
                                                                                                                                                                 to: (1) monitor the Services for violations of these Legal Terms; (2) take appropriate legal action against anyone who, in our sole discretion, violates the law or these Legal
                                                                                                                                                                 Terms, including without limitation, reporting such user to law enforcement authorities; (3) in our sole discretion and without limitation, refuse, restrict access to, limit the
                                                                                                                                                                  availability of, or disable (to the extent technologically feasible) any of your Contributions or any portion thereof; (4) in our sole discretion and without limitation, notice, or liability,
                                                                                                                                                                  to remove from the Services or otherwise disable all files and content that are excessive in size or are in any way burdensome to our systems; and (5) otherwise manage the Services in a manner
                                                                                                                                                                  designed to protect our rights and property and to facilitate the proper functioning of the Services.<br /><strong><span><strong><span><strong><span>15.</span></strong></span></strong> </span>PRIVACY POLICY</strong><br /><span>
                                                                                                                                                                    We care about data privacy and security. Please review our Privacy Policy:<strong> <a href="https://project.aislabs.com/privacy" target="_blank">https://project.aislabs.com/privacy</a></strong>.
                                                                                                                                                                     By using the Services, you agree to be bound by our Privacy Policy, which is incorporated into these Legal Terms. Please be advised the Services are hosted in the United States. If you access
                                                                                                                                                                     the Services from any other region of the world with laws or other requirements governing personal data collection, use, or disclosure that differ from applicable laws in <span>the United States</span>,
                                                                                                                                                                     then through your continued use of the Services, you are transferring your data to <span>the United States</span>, and you expressly consent to have your data transferred to and processed in
                                                                                                                                                                     <span>the United States</span>.<span></span></span><br /><strong><span><strong><span><strong><span><strong><span>16.</span></strong></span></strong></span> </strong>TERM AND TERMINATION</span></strong><br /><span>These Legal \
                                                                                                                                                                    Terms shall remain in full force and effect while you use the Services. WITHOUT LIMITING ANY OTHER PROVISION OF THESE LEGAL TERMS, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE
                                                                                                                                                                    SERVICES (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON FOR ANY REASON OR FOR NO REASON, INCLUDING WITHOUT LIMITATION FOR BREACH OF ANY REPRESENTATION, WARRANTY, OR COVENANT CONTAINED IN THESE LEGAL TERMS OR OF ANY APPLICABLE LAW
                                                                                                                                                                    OR REGULATION. WE MAY TERMINATE YOUR USE OR PARTICIPATION IN THE SERVICES OR DELETE YOUR ACCOUNT AND ANY CONTENT OR INFORMATION THAT YOU POSTED AT ANY TIME, WITHOUT WARNING, IN OUR SOLE DISCRETION.</span><br /><span>
                                                                                                                                                                    If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the
                                                                                                                                                                    third party. In addition to terminating or suspending your account, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.</span><br />
                                                                                                                                                                    <strong><span><strong><span><strong><span><strong><span>17.</span></strong></span></strong></span> </strong>MODIFICATIONS AND INTERRUPTIONS</span></strong><br /><span>We reserve the right to change, modify,
                                                                                                                                                                      or remove the contents of the Services at any time or for any reason at our sole discretion without notice. However, we have no obligation to update any information on our Services. We will not be liable to you or
                                                                                                                                                                      any third party for any modification, price change, suspension, or discontinuance of the Services.</span><br /><span>We cannot guarantee the Services will be available at all times. We may experience hardware, software,
                                                                                                                                                                        or other problems or need to perform maintenance related to the Services, resulting in interruptions, delays, or errors. We reserve the right to change, revise, update, suspend, discontinue, or otherwise modify the
                                                                                                                                                                        Services at any time or for any reason without notice to you. You agree that we have no liability whatsoever for any loss, damage, or inconvenience caused by your inability to access or use the Services during any
                                                                                                                                                                        downtime or discontinuance of the Services. Nothing in these Legal Terms will be construed to obligate us to maintain and support the Services or to supply any corrections, updates, or releases in connection therewith.</span><br />
                                                                                                                                                                        <strong><span><strong><span><strong><span><strong><span>18.</span></strong></span></strong></span> </strong>GOVERNING LAW</span></strong><br /><span></span><span>These Legal Terms and your use of the Services are
                                                                                                                                                                          governed by and construed in accordance with the laws of the State of Illinois applicable to agreements made and to be entirely performed within <span>the State of Illinois<span>, </span>without regard to its conflict of law principles.</span><br />
                                                                                                                                                                          <strong><span><strong><span><strong><span><strong><span>19.</span></strong></span></strong></span> </strong>DISPUTE RESOLUTION</span></strong><br />
                                                                                                                                                                          <strong>Binding Arbitration</strong><br /><span></span><span>If the Parties are unable to resolve a Dispute through informal negotiations, the Dispute (except those Disputes expressly excluded below) will be finally
                                                                                                                                                                            and exclusively resolved by binding arbitration. YOU UNDERSTAND THAT WITHOUT THIS PROVISION, YOU WOULD HAVE THE RIGHT TO SUE IN COURT AND HAVE A JURY TRIAL. The arbitration shall be commenced and conducted under
                                                                                                                                                                            the Commercial Arbitration Rules of the American Arbitration Association ("AAA") and, where appropriate, the AAA’s Supplementary Procedures for Consumer Related Disputes ("AAA Consumer Rules"), both of which are
                                                                                                                                                                            available at the <span><a href="http://www.adr.org" rel="noopener noreferrer" target="_blank">American Arbitration Association (AAA) website</a></span>.
                                                                                                                                                                            Your arbitration fees and your share of arbitrator compensation shall be governed by the AAA Consumer Rules and, where appropriate, limited by the AAA Consumer Rules. The arbitration may be conducted in person, through the
                                                                                                                                                                            submission of documents, by phone, or online. The arbitrator will make a decision in writing, but need not provide a statement of reasons unless requested by either Party. The arbitrator must follow applicable law, and any
                                                                                                                                                                             award may be challenged if the arbitrator fails to do so. Except where otherwise required by the applicable AAA rules or applicable law, the arbitration will take place in Cook, Illinois. Except as otherwise provided herein,
                                                                                                                                                                             the Parties may litigate in court to compel arbitration, stay proceedings pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator.</span><br /><span>If for any reason, a
                                                                                                                                                                              Dispute proceeds in court rather than arbitration, the Dispute shall be commenced or prosecuted in the</span><span> state and federal courts</span><span> located in</span> Cook<span>,</span> Illinois<span>, and the Parties
                                                                                                                                                                                hereby consent to, and waive all defenses of lack of personal jurisdiction, and forum non conveniens with respect to venue and jurisdiction in such state and federal courts. Application of the United Nations Convention
                                                                                                                                                                                on Contracts for the International Sale of Goods and the Uniform Computer Information Transaction Act (UCITA) are excluded from these Legal Terms.</span><br /><span>In no event shall any Dispute brought by either Party
                                                                                                                                                                                  related in any way to the Services be commenced more than one (1) years after the cause of action arose. If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any
                                                                                                                                                                                  Dispute falling within that portion of this provision found to be illegal or unenforceable and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above,
                                                                                                                                                                                  and the Parties agree to submit to the personal jurisdiction of that court.<br /><strong>Restrictions</strong><br />
                                                                                                                                                                                  The Parties agree that any arbitration shall be limited to the Dispute between the Parties individually. To the full extent permitted by law, (a) no arbitration shall be joined with any other proceeding; (b)
                                                                                                                                                                                  there is no right or authority for any Dispute to be arbitrated on a class-action basis or to utilize class action procedures; and (c) there is no right or authority for any Dispute to be brought in a purported
                                                                                                                                                                                  representative capacity on behalf of the general public or any other persons.<br /><strong>Exceptions to Arbitration</strong><br />The Parties agree that the following Disputes are not subject to the above
                                                                                                                                                                                  provisions concerning binding arbitration: (a) any Disputes seeking to enforce or protect, or concerning the validity of, any of the intellectual property rights of a Party; (b) any Dispute related to, or
                                                                                                                                                                                  arising from, allegations of theft, piracy, invasion of privacy, or unauthorized use; and (c) any claim for injunctive relief. If this provision is found to be illegal or unenforceable, then neither Party
                                                                                                                                                                                  will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable and such Dispute shall be decided by a court of competent jurisdiction within the
                                                                                                                                                                                  courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.<br /><strong><span><strong><span><strong><span><strong><span>20.</span></strong></span></strong></span> 
                                                                                                                                                                                  </strong>CORRECTIONS</span></strong><br />There may be information on the Services that contains typographical errors, inaccuracies, or omissions, including descriptions, pricing, availability, and various other information.
                                                                                                                                                                                  We reserve the right to correct any errors, inaccuracies, or omissions and to change or update the information on the Services at any time, without prior notice.<br /><span><strong><span><strong><span><strong><span>21.</span>
                                                                                                                                                                                  </strong></span></strong></span> DISCLAIMER</strong></span><br /><span>THE SERVICES ARE PROVIDED ON AN AS-IS AND AS-AVAILABLE BASIS. YOU AGREE THAT YOUR USE OF THE SERVICES WILL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT
                                                                                                                                                                                    PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SERVICES AND YOUR USE THEREOF, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
                                                                                                                                                                                    AND NON-INFRINGEMENT. WE MAKE NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE SERVICES' CONTENT OR THE CONTENT OF ANY WEBSITES OR MOBILE APPLICATIONS LINKED TO THE SERVICES AND WE WILL ASSUME NO
                                                                                                                                                                                    LIABILITY OR RESPONSIBILITY FOR ANY (1) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT AND MATERIALS, (2) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SERVICES, (3)
                                                                                                                                                                                    ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (4) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICES, (5) ANY
                                                                                                                                                                                    BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SERVICES BY ANY THIRD PARTY, AND/OR (6) ANY ERRORS OR OMISSIONS IN ANY CONTENT AND MATERIALS OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED
                                                                                                                                                                                    AS A RESULT OF THE USE OF ANY CONTENT POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICES. WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A
                                                                                                                                                                                    THIRD PARTY THROUGH THE SERVICES, ANY HYPERLINKED WEBSITE, OR ANY WEBSITE OR MOBILE APPLICATION FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY
                                                                                                                                                                                    TRANSACTION BETWEEN YOU AND ANY THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION
                                                                                                                                                                                    WHERE APPROPRIATE.</span><br /><strong><span><strong><span><strong><span><strong><span>22.</span></strong></span></strong></span> </strong>LIMITATIONS OF LIABILITY</span></strong><br /><span>
  <span>IN NO EVENT WILL WE OR OUR DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES,
    INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, OR OTHER DAMAGES ARISING FROM YOUR USE OF THE SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</span> <span >NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE
AMOUNT PAID, IF ANY, BY YOU TO US
<span>
  DURING THE six (6) mONTH PERIOD PRIOR TO ANY CAUSE OF ACTION ARISING</span>.</span> 
  </span><span >
    CERTAIN US STATE LAWS AND INTERNATIONAL LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS OR
    LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.</span></span><span ></span></span><br /><strong><span><strong>
      <span><strong><span><strong>
        <span>23.</span></strong></span></strong></span> </strong>INDEMNIFICATION</span></strong><br /><span style="font-size:11.0pt;line-height:115%;font-family:Arial;
">You agree to
defend, indemnify, and hold us harmless, including our subsidiaries,
affiliates, and all of our respective officers, agents, partners, and
employees, from and against any loss, damage, liability, claim, or demand, including
reasonable attorneys’ fees and expenses, made by any third party due to or
arising out of: (<span>1</span>) use of the Services; (<span>2</span>) breach of these Legal Terms; (<span>3</span>)
any breach of your representations and warranties set forth in these Legal Terms; (<span>4</span>) your violation of the rights of a third party, including but not limited to intellectual property rights; or
(<span>5</span>) any overt harmful act toward any other user of the Services with whom you connected via the Services. Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive
defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense of such claims. We will use reasonable efforts to notify you of any such claim, action, or proceeding
which is subject to this indemnification upon becoming aware of it.</span><br /><strong>
  <span><strong><span><strong><span><strong>
    <span>24.</span></strong></span></strong></span> </strong>USER DATA</span></strong><br /><span>We will maintain
certain data that you transmit to the Services for the purpose of managing the
performance of the Services, as well as data relating to your use of the Services. Although we perform regular routine backups
of data, you are solely responsible for all data that you transmit or that
relates to any activity you have undertaken using the Services. You agree
that we shall have no liability to you for any loss or corruption of any such
data, and you hereby waive any right of action against us arising from any such
loss or corruption of such data.</span><br />
<strong><span><strong><span><strong><span><strong><span>25.</span></strong></span></strong></span> </strong>ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES</span></strong><br /><span>
  isiting the Services, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide
  to you electronically, via email and on the Services, satisfy any legal requirement that such communication be in writing. YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES,
  POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE SERVICES. You hereby waive any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction which require an original signature
  or delivery or retention of non-electronic records, or to payments or the granting of credits by any means other than electronic means.</span><br />
  <strong><span><strong><span><strong><span><strong><span>26.</span></strong></span></strong></span> </strong>CALIFORNIA USERS AND RESIDENTS</span></strong><br />
  <span>If any complaint
with us is not satisfactorily resolved, you can contact the Complaint
Assistance Unit of the Division of Consumer Services of the California
Department of Consumer Affairs in writing at 1625 North Market Blvd., Suite N
112, Sacramento, California 95834 or by telephone at (800) 952-5210 or (916)
445-1254.</span><br /><strong><span><strong><span><strong><span><strong><span>27.</span></strong></span></strong></span> 
</strong>MISCELLANEOUS</span></strong><br /><span>These Legal Terms and any policies or operating rules posted by us on the Services or in respect to the Services constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce
  any right or provision of these Legal Terms shall not operate as a waiver of such right or provision. These Legal Terms operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be
  responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control. If any provision or part of a provision of these Legal Terms is determined to be unlawful, void, or unenforceable, that provision or part of the
  provision is deemed severable from these Legal Terms and does not affect the validity and enforceability of any remaining provisions. There is no joint venture, partnership, employment or agency relationship created between you and us as a result of these Legal
  Terms or use of the Services. You agree that these Legal Terms will not be construed against us by virtue of having drafted them. You hereby waive any and all defenses you may have based on the electronic form of these Legal Terms and the lack of signing by the
  parties hereto to execute these Legal Terms.</span><span></span><br /><strong><span><span><strong><span><strong><span><strong><span>28.</span></strong></span></strong>
</span> </strong>CONTACT US</span></span></strong><br /><span>In order to resolve a complaint regarding the Services or to receive further information regarding use of the Services, please contact us at:</span>
<br /><span><strong>All Information Services LLC</strong>
</span>




      </q-page-container>
  </q-page>
</template>
